thehyve/transmart-core

open-api/swagger.json
open-api/swagger.yaml
open-api/swagger_spec.js
transmart-rest-api-e2e/src/test/groovy/base/RESTSpec.groovy
transmart-rest-api-e2e/src/test/groovy/tests/rest/v2/AggregatedSpec.groovy
transmart-rest-api-e2e/src/test/groovy/tests/rest/v2/ObservationCountsSpec.groovy
transmart-rest-api-e2e/src/test/groovy/tests/rest/v2/ObservationSpec.groovy
transmart-rest-api-e2e/src/test/groovy/tests/rest/v2/PatientsSpec.groovy
transmart-rest-api/grails-app/controllers/org/transmartproject/rest/AbstractQueryController.groovy
transmart-rest-api/grails-app/controllers/org/transmartproject/rest/PatientQueryController.groovy
transmart-rest-api/grails-app/controllers/org/transmartproject/rest/QueryController.groovy
transmart-rest-api/grails-app/controllers/org/transmartproject/rest/RestApiUrlMappings.groovy
transmart-rest-api/src/integration-test/groovy/org/transmartproject/rest/QueryControllerSpec.groovy

Fix GBD-4 - an issue with URL length limit
Adding support for both POST and GET for calls that can reach this limit

Gb long constraints support

---

transmart-solr-indexing/grails-app/controllers/org/transmartproject/search/FacetsSearchController.groovy
transmartApp/grails-app/assets/javascripts/datasetExplorer/i2b2common.js
transmartApp/grails-app/assets/javascripts/rwgsearch.js
transmartApp/grails-app/services/org/transmartfoundation/status/SolrStatusService.groovy
transmartApp/grails-app/views/RWG/index.gsp
transmartApp/grails-app/views/datasetExplorer/datasetExplorer.gsp

fixed the Facet search in transmartApp

Lodz2 dev datacommons solr filters

---

transmartApp/grails-app/assets/stylesheets/admin.css
transmartApp/grails-app/assets/stylesheets/main.css
transmartApp/grails-app/conf/application.groovy
transmartApp/grails-app/controllers/org/transmartproject/app/OauthAdminController.groovy
transmartApp/grails-app/controllers/org/transmartproject/app/UserApplicationsController.groovy
transmartApp/grails-app/services/org/transmartproject/security/OAuth2SyncService.groovy
transmartApp/grails-app/views/layouts/_adminnavbar.gsp
transmartApp/grails-app/views/layouts/_utilitiesMenu.gsp
transmartApp/grails-app/views/layouts/utilities.gsp
transmartApp/grails-app/views/oauthAdmin/edit.gsp
transmartApp/grails-app/views/oauthAdmin/list.gsp
transmartApp/grails-app/views/oauthAdmin/view.gsp
transmartApp/grails-app/views/userApplications/list.gsp

Bring management of REST clients to 17.1

---

transmartApp/grails-app/conf/application.groovy
transmartApp/grails-app/controllers/org/transmartproject/app/OntologyController.groovy
transmartApp/grails-app/services/com/recomdata/transmart/data/export/ExportMetadataService.groovy
transmartApp/grails-app/views/ontology/_showDataTypes.gsp
transmartApp/grails-app/views/ontology/_showDefinition.gsp

Source: https://github.com/thehyve/naa-transmartApp/pull/39/commits

Bring configuring and retrieval of request access link to 17.1 backend

---

transmartApp/grails-app/services/org/transmartproject/app/I2b2HelperService.groovy

Fix failing summary statistics 

---

transmart-core-db-tests/src/integration-test/groovy/org/transmartproject/db/multidimquery/HibernateCriteriaQueryBuilderSpec.groovy
transmart-core-db-tests/src/integration-test/groovy/org/transmartproject/db/multidimquery/QueryServiceSpec.groovy
transmart-core-db-tests/src/test/groovy/org/transmartproject/db/multidimquery/QuerySpec.groovy
transmart-core-db/grails-app/services/org/transmartproject/db/clinical/MultidimensionalDataResourceService.groovy
transmart-core-db/src/integration-test/groovy/org/transmartproject/db/multidimquery/DimensionsPgSpec.groovy
transmart-core-db/src/integration-test/groovy/org/transmartproject/db/multidimquery/QueryService2Spec.groovy
transmart-core-db/src/integration-test/groovy/org/transmartproject/db/multidimquery/QueryServicePgSpec.groovy
transmart-core-db/src/main/groovy/org/transmartproject/db/multidimquery/DimensionImpl.groovy
transmart-core-db/src/main/groovy/org/transmartproject/db/multidimquery/query/Constraint.groovy
transmart-core-db/src/main/groovy/org/transmartproject/db/multidimquery/query/DimensionMetadata.groovy
transmart-core-db/src/main/groovy/org/transmartproject/db/multidimquery/query/HibernateCriteriaQueryBuilder.groovy
transmart-rest-api-e2e/src/test/groovy/tests/rest/v2/QueryLanguage.groovy
transmart-rest-api-e2e/src/test/groovy/tests/rest/v2/hypercube/ConstraintSpec.groovy

Finish the inline selection functionality and add proper tests.
I also took the opportunity to fold ConstraintDimension into the DimensionImpl classes.

Inline selections - remaining stuff

---

transmart-rest-api/build.gradle
transmart-rest-api/grails-app/controllers/org/transmartproject/rest/RestApiUrlMappings.groovy
transmartApp/build.gradle
transmartApp/grails-app/conf/application.groovy

the versioning feature wasn't yet working as designed

Versioning fixes

---

transmart-core-db-tests/src/integration-test/groovy/org/transmartproject/db/multidimquery/QueryServiceSpec.groovy

The test that was missing in [PR#37](https://github.com/thehyve/transmart-core/pull/37)

Add core-db-tests test for getPatientSets query

---

transmart-core-api/src/main/groovy/org/transmartproject/core/ontology/OntologyTermTag.groovy
transmart-core-api/src/main/groovy/org/transmartproject/core/ontology/OntologyTermTagsResource.groovy
transmart-core-api/src/main/groovy/org/transmartproject/core/tree/TreeNode.groovy
transmart-core-api/src/main/groovy/org/transmartproject/core/tree/TreeResource.groovy
transmart-core-db-tests/src/integration-test/groovy/org/transmartproject/db/multidimquery/QueryServiceSpec.groovy
transmart-core-db/grails-app/domain/org/transmartproject/db/ontology/I2b2Secure.groovy
transmart-core-db/grails-app/services/org/transmartproject/db/ontology/OntologyTermTagsResourceService.groovy
transmart-core-db/grails-app/services/org/transmartproject/db/tree/TreeCacheService.groovy
transmart-core-db/grails-app/services/org/transmartproject/db/tree/TreeService.groovy
transmart-core-db/src/integration-test/groovy/org/transmartproject/db/tree/TreeServiceTest.groovy
transmart-core-db/src/main/groovy/org/transmartproject/db/multidimquery/query/Constraint.groovy
transmart-core-db/src/main/groovy/org/transmartproject/db/tree/TreeNodeConstraintHelper.groovy
transmart-core-db/src/main/groovy/org/transmartproject/db/tree/TreeNodeImpl.groovy
transmart-rest-api-e2e/src/test/groovy/config/Config.groovy
transmart-rest-api-e2e/src/test/groovy/tests/rest/v2/TreeNodesSpec.groovy
transmart-rest-api/grails-app/controllers/org/transmartproject/rest/RestApiUrlMappings.groovy
transmart-rest-api/grails-app/controllers/org/transmartproject/rest/TreeController.groovy
transmart-rest-api/src/main/groovy/org/transmartproject/rest/marshallers/ConstraintMarshaller.groovy
transmart-rest-api/src/main/groovy/org/transmartproject/rest/marshallers/MarshallersRegistrar.groovy
transmart-rest-api/src/main/groovy/org/transmartproject/rest/marshallers/TreeNodeMarshaller.groovy

- Added endpoint for clearing the tree node cache
- Refactored tree node code
- Changed logic to fetch study id for a study node: dimcode if table is 'study', sourcesystemCd if table is 'concept_dimension'.

Clear tree node cache

---

transmart-core-db/src/integration-test/groovy/org/transmartproject/db/multidimquery/QueryServicePgSpec.groovy
transmart-core-db/src/main/groovy/org/transmartproject/db/multidimquery/DimensionImpl.groovy
transmart-core-db/src/main/groovy/org/transmartproject/db/multidimquery/query/HibernateCriteriaQueryBuilder.groovy
transmart-rest-api-e2e/src/test/groovy/base/RESTSpec.groovy

Add a possibility to query date observations to the `Time` constraint.

Add possibility to query value dimension. Date to number conversion. 

---

transmart-copy/build.gradle
transmart-copy/src/test/groovy/org/transmartproject/copy/CopySpec.groovy
transmart-core-api/src/main/groovy/org/transmartproject/core/dataquery/VariableMetadata.groovy
transmart-core-api/src/test/groovy/org/transmartproject/core/dataquery/VariableMetadataTests.groovy
transmart-core-db/grails-app/domain/org/transmartproject/db/i2b2data/ConceptDimension.groovy

Whole number like '-1.0' should be parsed to integer as well.

Improve concept blob parsing.

---

transmart-core-db-tests/src/integration-test/groovy/org/transmartproject/db/multidimquery/HibernateCriteriaQueryBuilderSpec.groovy
transmart-core-db/grails-app/domain/org/transmartproject/db/i2b2data/Study.groovy
transmart-core-db/grails-app/services/org/transmartproject/db/clinical/MultidimensionalDataResourceService.groovy
transmart-core-db/src/integration-test/groovy/org/transmartproject/db/multidimquery/QueryServicePgSpec.groovy
transmart-core-db/src/main/groovy/org/transmartproject/db/accesscontrol/AccessControlChecks.groovy
transmart-core-db/src/main/groovy/org/transmartproject/db/multidimquery/query/HibernateCriteriaQueryBuilder.groovy

Based on [this changes](https://github.com/thehyve/transmart-core/pull/129)

Study shortcut

---

transmart-copy/src/main/groovy/org/transmartproject/copy/Copy.groovy
transmart-copy/src/test/groovy/org/transmartproject/copy/CopySpec.groovy

Initialize databse in the counstructor.

Fix NPE when run from the command line.

---

transmart-rest-api-e2e/src/test/groovy/tests/rest/v2/RelationSpec.groovy

added 2 tests to verify perental connections

add tests for pedigree

---

transmart-core-db/src/main/groovy/org/transmartproject/db/multidimquery/query/Constraint.groovy
transmart-core-db/src/main/groovy/org/transmartproject/db/multidimquery/query/ConstraintBuilder.groovy
transmart-core-db/src/main/groovy/org/transmartproject/db/multidimquery/query/ConstraintSerialiser.groovy
transmart-core-db/src/test/groovy/org/transmartproject/db/multidimquery/ConstraintSerialiserSpec.groovy

JSON serialisation for constraints was broken for subclasses
of Combination, which caused issues with caching query results.

Apply constraint serialisation bug from luke-dev branch.

---

transmart-rest-api/src/main/groovy/org/transmartproject/rest/serialization/tabular/TabularResultSPSSSerializer.groovy
transmart-rest-api/src/test/groovy/org/transmartproject/rest/serialization/tabular/TabularResultSPSSSerializerSpec.groovy

- Fix SPSS export for string values if no column width is specified
- Combine SPS and SAV export
- Remove failing test after previous change (due to SAV export depending on application configuration)
- Statically compile the SPSS exporter

Spss fixes

---

transmart-core-db/src/main/groovy/org/transmartproject/db/multidimquery/query/CanonicalConstraintRewriter.groovy
transmart-core-db/src/main/groovy/org/transmartproject/db/multidimquery/query/Constraint.groovy
transmart-core-db/src/main/groovy/org/transmartproject/db/multidimquery/query/ConstraintComparator.groovy
transmart-core-db/src/main/groovy/org/transmartproject/db/multidimquery/query/NormaliseConstraintRewriter.groovy
transmart-core-db/src/test/groovy/org/transmartproject/db/multidimquery/QueryRewriterSpec.groovy

- Add constraint canoniser class.

Add constraint canoniser class.

---

open-api/swagger.json
open-api/swagger.yaml
open-api/swagger_spec.js
transmart-core-api/src/main/groovy/org/transmartproject/core/multidimquery/CategoricalValueAggregates.groovy
transmart-core-db/grails-app/services/org/transmartproject/db/clinical/MultidimensionalDataResourceService.groovy
transmart-core-db/src/integration-test/groovy/org/transmartproject/db/multidimquery/QueryServicePgSpec.groovy

Add nullValueCounts to aggregatePerConcept results 

---

open-api/swagger.json
open-api/swagger.yaml
open-api/swagger_spec.js
transmart-core-db/grails-app/services/org/transmartproject/db/clinical/SurveyTableColumnService.groovy
transmart-core-db/src/integration-test/groovy/org/transmartproject/db/multidimquery/SurveyTableViewSpec.groovy
transmart-rest-api/grails-app/controllers/org/transmartproject/rest/ExportController.groovy
transmart-rest-api/grails-app/controllers/org/transmartproject/rest/QueryController.groovy
transmart-rest-api/grails-app/services/org/transmartproject/rest/HypercubeDataSerializationService.groovy
transmart-rest-api/grails-app/services/org/transmartproject/rest/SurveyTableViewDataSerializationService.groovy
transmart-rest-api/grails-app/services/org/transmartproject/rest/dataExport/ExportAsyncJobService.groovy
transmart-rest-api/grails-app/services/org/transmartproject/rest/dataExport/ExportService.groovy
transmart-rest-api/src/main/groovy/org/transmartproject/rest/serialization/DataSerializer.groovy

Add a flag for export job call to specify whether to include measurement date columns

---

transmart-core-db/grails-app/services/org/transmartproject/db/clinical/AggregateDataService.groovy

- Use constraint factory in aggregate data service.
- Generate new patient set and cache counts for it.

Luke constraint parser

---

transmart-copy/README.md
transmart-copy/src/main/groovy/org/transmartproject/copy/Copy.groovy
transmart-copy/src/main/groovy/org/transmartproject/copy/table/Concepts.groovy
transmart-copy/src/main/groovy/org/transmartproject/copy/table/TreeNodes.groovy
transmart-copy/src/main/resources/examples/SURVEY/i2b2metadata/.~lock.i2b2_secure.tsv#
transmart-copy/src/test/groovy/org/transmartproject/copy/CopySpec.groovy

This PR is based on [the single transaction PR](https://github.com/thehyve/transmart-core/pull/149).

Update concept paths

---

docs/index.md
docs/installation.md
transmart-data/README.md

- add external links to other installation guides
- add versions of dependencies
- other small modifications
Addresses TMNP-36 and part of TMNP-38.

Documentation enhancements

---

transmart-data/updatedb/README.md
transmart-data/updatedb/release-17.12/README.md
transmart-data/updatedb/release-17.12/oracle/Makefile
transmart-data/updatedb/release-17.12/oracle/data_migration.sql
transmart-data/updatedb/release-17.12/postgres/Makefile
transmart-data/updatedb/release-17.12/postgres/data_migration.sql

Add migration script updates for 17.12 release

---

transmart-data/config/DataSource.groovy.php
transmart-server/grails-app/conf/application.groovy

It might be turned on for development envirounment when it's needed.

Remove sql logging on oauth2 data set.

---

build.gradle
settings.gradle
transmart-notifications/build.gradle
transmart-notifications/grails-app/conf/application.yml
transmart-notifications/grails-app/conf/logback.groovy
transmart-notifications/grails-app/conf/spring/resources.groovy
transmart-notifications/grails-app/init/transmart/notifications/Application.groovy
transmart-notifications/grails-app/init/transmart/notifications/BootStrap.groovy
transmart-notifications/grails-app/jobs/org/transmart/notifications/QuerySetSubscriptionDailyJob.groovy
transmart-notifications/grails-app/jobs/org/transmart/notifications/QuerySetSubscriptionWeeklyJob.groovy
transmart-notifications/grails-app/services/org/transmart/notifications/QuerySetSubscriptionMailService.groovy
transmart-notifications/src/main/groovy/org/transmart/notifications/TransmartNotificationsGrailsPlugin.groovy
transmart-server/build.gradle
transmart-server/grails-app/conf/application.groovy

Move query subscription logic from tm-server to tm-notifications plugin

---

transmart-notifications/build.gradle

Fixes https://jira.thehyve.nl/browse/TMT-101.

Fix missing resources on login page.

---

transmart-core-db/src/main/groovy/org/transmartproject/db/multidimquery/HypercubeImpl.groovy

Refactor the hypercube to not use closures

Refactor hypercube closures

---

open-api/swagger.json
open-api/swagger.yaml
open-api/swagger_spec.js
transmart-core-api/src/main/groovy/org/transmartproject/core/userquery/UserQuery.groovy
transmart-core-db/grails-app/domain/org/transmartproject/db/querytool/Query.groovy
transmart-core-db/src/integration-test/groovy/org/transmartproject/db/querytool/QueryPgSpec.groovy
transmart-data/ddl/oracle/biomart_user/query.sql
transmart-data/ddl/postgres/biomart_user/query.sql
transmart-data/updatedb/dev/README.md
transmart-data/updatedb/dev/oracle/Makefile
transmart-data/updatedb/dev/oracle/data_migration.sql
transmart-data/updatedb/dev/postgres/Makefile
transmart-data/updatedb/dev/postgres/data_migration.sql
transmart-rest-api-e2e/src/test/groovy/tests/rest/QueryLanguage.groovy
transmart-rest-api-e2e/src/test/groovy/tests/rest/v2/UserQuerySpec.groovy
transmart-rest-api/grails-app/controllers/org/transmartproject/rest/UserQueryController.groovy

To support storing of a data table state in the UI
TMT-85, TMT-86

Add queryBlob to user queries

---

open-api/contributers.md
open-api/swagger.json
open-api/swagger.yaml
open-api/swagger_spec.js
transmart-core-api/src/main/groovy/org/transmartproject/core/dataquery/SortOrder.groovy
transmart-core-api/src/main/groovy/org/transmartproject/core/multidimquery/Hypercube.groovy
transmart-core-api/src/main/groovy/org/transmartproject/core/multidimquery/HypercubeValue.groovy
transmart-core-api/src/main/groovy/org/transmartproject/core/multidimquery/MultiDimensionalDataResource.groovy
transmart-core-db-tests/build.gradle
transmart-core-db-tests/grails-app/conf/application.yml
transmart-core-db-tests/src/integration-test/groovy/org/transmartproject/db/multidimquery/QueryServiceSpec.groovy
transmart-core-db/grails-app/services/org/transmartproject/db/clinical/MultidimensionalDataResourceService.groovy
transmart-core-db/src/integration-test/groovy/org/transmartproject/db/multidimquery/SurveyTableViewSpec.groovy
transmart-core-db/src/main/groovy/org/transmartproject/db/multidimquery/DimensionImpl.groovy
transmart-core-db/src/main/groovy/org/transmartproject/db/multidimquery/EmptyHypercube.groovy
transmart-core-db/src/main/groovy/org/transmartproject/db/multidimquery/HddTabularResultHypercubeAdapter.groovy
transmart-core-db/src/main/groovy/org/transmartproject/db/multidimquery/HypercubeImpl.groovy
transmart-rest-api/grails-app/controllers/org/transmartproject/rest/QueryController.groovy
transmart-rest-api/grails-app/services/org/transmartproject/rest/HypercubeDataSerializationService.groovy
transmart-rest-api/grails-app/services/org/transmartproject/rest/SurveyTableViewDataSerializationService.groovy
transmart-rest-api/src/integration-test/groovy/org/transmartproject/rest/QueryControllerSpec.groovy
transmart-rest-api/src/main/groovy/org/transmartproject/rest/hypercubeProto/ObservationsProto.java
transmart-rest-api/src/main/groovy/org/transmartproject/rest/misc/RequestUtils.groovy
transmart-rest-api/src/main/groovy/org/transmartproject/rest/protobuf/HighDimProtos.java
transmart-rest-api/src/main/groovy/org/transmartproject/rest/serialization/HypercubeJsonSerializer.groovy
transmart-rest-api/src/main/groovy/org/transmartproject/rest/serialization/HypercubeProtobufSerializer.groovy
transmart-rest-api/src/protobuf/highdim/highdim.proto
transmart-rest-api/src/protobuf/v2/observations.proto
transmart-rest-api/src/test/groovy/org/transmartproject/rest/misc/RequestUtilsSpec.groovy
transmart-rest-api/src/test/groovy/org/transmartproject/rest/protobug/ObservationsBuilderTests.groovy

Encode the sorting used in the serialized hypercubes (json and protobuf).
This PR should go on top of the first sorting PR.

Sorting part 2

---

transmart-core-db-tests/src/integration-test/groovy/org/transmartproject/db/dataquery/highdim/mrna/MrnaGeneDataConstraintSpec.groovy
transmart-core-db-tests/src/test/groovy/org/transmartproject/db/dataquery/highdim/DefaultHighDimensionTabularResultSpec.groovy
transmart-core-db-tests/src/test/groovy/org/transmartproject/db/dataquery/highdim/RepeatedEntriesCollectingTabularResultSpec.groovy
transmart-core-db/src/main/groovy/org/transmartproject/db/dataquery/CollectingTabularResult.groovy
transmart-core-db/src/main/groovy/org/transmartproject/db/dataquery/MultiTabularResult.groovy
transmart-core-db/src/main/groovy/org/transmartproject/db/dataquery/clinical/TerminalClinicalVariablesTabularResult.groovy
transmart-core-db/src/main/groovy/org/transmartproject/db/dataquery/highdim/DefaultHighDimensionTabularResult.groovy
transmart-core-db/src/main/groovy/org/transmartproject/db/dataquery/highdim/RepeatedEntriesCollectingTabularResult.groovy
transmart-core-db/src/main/groovy/org/transmartproject/db/dataquery/highdim/acgh/AcghModule.groovy
transmart-core-db/src/main/groovy/org/transmartproject/db/dataquery/highdim/metabolite/MetaboliteModule.groovy
transmart-core-db/src/main/groovy/org/transmartproject/db/dataquery/highdim/mirna/AbstractMirnaSharedModule.groovy
transmart-core-db/src/main/groovy/org/transmartproject/db/dataquery/highdim/mrna/MrnaModule.groovy
transmart-core-db/src/main/groovy/org/transmartproject/db/dataquery/highdim/protein/ProteinModule.groovy
transmart-core-db/src/main/groovy/org/transmartproject/db/dataquery/highdim/rbm/RbmModule.groovy
transmart-core-db/src/main/groovy/org/transmartproject/db/dataquery/highdim/rnaseq/RnaSeqModule.groovy
transmart-core-db/src/main/groovy/org/transmartproject/db/dataquery/highdim/rnaseq/transcript/RnaSeqTranscriptModule.groovy
transmart-core-db/src/main/groovy/org/transmartproject/db/dataquery/highdim/rnaseqcog/RnaSeqCogModule.groovy
transmart-core-db/src/main/groovy/org/transmartproject/db/dataquery/highdim/snp_lz/SnpLzModule.groovy
transmart-core-db/src/main/groovy/org/transmartproject/db/dataquery/highdim/tworegion/TwoRegionModule.groovy
transmart-core-db/src/main/groovy/org/transmartproject/db/dataquery/highdim/vcf/CohortProjection.groovy
transmart-core-db/src/main/groovy/org/transmartproject/db/dataquery/highdim/vcf/VcfModule.groovy

Refactor TabularResult implementations to use @CompileStatic and not use closures

Tabular result remove closures

---

transmart-core-api/src/main/groovy/org/transmartproject/core/multidimquery/DataTable.groovy
transmart-core-db-tests/src/integration-test/groovy/org/transmartproject/db/multidimquery/DataTableSpec.groovy
transmart-core-db/grails-app/services/org/transmartproject/db/clinical/MultidimensionalDataResourceService.groovy
transmart-core-db/src/main/groovy/org/transmartproject/db/multidimquery/DataTableImpl.groovy
transmart-core-db/src/test/groovy/org/transmartproject/db/multidimquery/HypercubeTabularResultViewSpec.groovy
transmart-rest-api/src/main/groovy/org/transmartproject/rest/hypercubeProto/ObservationsProto.java
transmart-rest-api/src/main/groovy/org/transmartproject/rest/serialization/HypercubeProtobufSerializer.groovy
transmart-rest-api/src/main/groovy/org/transmartproject/rest/serialization/Type.groovy
transmart-rest-api/src/protobuf/v2/observations.proto
transmart-rest-api/src/test/groovy/org/transmartproject/rest/protobug/ObservationsBuilderTests.groovy

Fix tests that were failing by supporting serializing of maps/objects to protobuf messages. 
All tests should pass again after this.

Fix protobuf tests

---

open-api/swagger.json
open-api/swagger.yaml
open-api/swagger_spec.js
transmart-rest-api-e2e/src/test/groovy/tests/rest/v2/StudiesSpec.groovy
transmart-rest-api/grails-app/controllers/org/transmartproject/rest/StudyQueryController.groovy
transmart-rest-api/src/integration-test/groovy/org/transmartproject/rest/MDStudyControllerSpec.groovy

Replace `/v2/studies/studyIds?studyIds=foo&studyIds=bar ` with `/v2/studies/studyIds?studyIds=["foo","bar"] `

Replace studyIds params in /v2/studies/studyIds call with a JSON encoded list

---

transmart-core-api/src/main/groovy/org/transmartproject/core/ontology/StudyMetadata.groovy
transmart-core-api/src/main/groovy/org/transmartproject/core/ontology/TabularRepresentationMetadata.groovy
transmart-core-api/src/test/groovy/org/transmartproject/core/ontology/StudyMetadataTests.groovy
transmart-data/test_data/studies/SHARED_CONCEPTS_STUDY_A/i2b2demodata/study.tsv
transmart-rest-api-e2e/src/test/groovy/tests/rest/v2/StudiesSpec.groovy

Add storage of a study specific table representation

---

transmart-core-db-tests/src/test/groovy/org/transmartproject/db/multidimquery/AbstractDataTableSpec.groovy
transmart-core-db/src/integration-test/groovy/org/transmartproject/db/multidimquery/DataTablePgSpec.groovy
transmart-core-db/src/main/groovy/org/transmartproject/db/multidimquery/AbstractDataTable.groovy
transmart-core-db/src/main/groovy/org/transmartproject/db/multidimquery/DimensionImpl.groovy

Dimension keys and elements are nullable, so they cannot be of type
ImmutableList, which does not support null values.
Issue description: TMT-207

 Replace ImmutableList with Collections.unmodifiableList

---

open-api/swagger.json
open-api/swagger.yaml
open-api/swagger_spec.js
transmart-core-api/src/main/groovy/org/transmartproject/core/config/SystemResource.groovy
transmart-core-api/src/main/groovy/org/transmartproject/core/multidimquery/MultiDimensionalDataResource.groovy
transmart-core-db/grails-app/services/org/transmartproject/db/clinical/AggregateDataOptimisationsService.groovy
transmart-core-db/grails-app/services/org/transmartproject/db/clinical/MultidimensionalDataResourceService.groovy
transmart-core-db/grails-app/services/org/transmartproject/db/support/SystemService.groovy
transmart-core-db/grails-app/services/org/transmartproject/db/userqueries/UserQuerySetService.groovy
transmart-core-db/src/integration-test/groovy/org/transmartproject/db/multidimquery/QueryServicePgSpec.groovy
transmart-data/ddl/postgres/biomart_user/materialized_views/study_concept_bitset.sql
transmart-rest-api/grails-app/controllers/org/transmartproject/rest/RestApiUrlMappings.groovy
transmart-rest-api/grails-app/controllers/org/transmartproject/rest/SystemController.groovy
transmart-rest-api/grails-app/controllers/org/transmartproject/rest/TreeController.groovy

TMT-163
- clear patient sets
- clear patient bitset
- clear caches
- scan for user subscribed queries updates

 Add a call for updates required after data loading

---

transmart-rest-api/grails-app/services/org/transmartproject/rest/dataExport/ExportService.groovy

Fix for [TMT-225](https://jira.thehyve.nl/browse/TMT-225)

Fix export

---

transmart-notifications/grails-app/conf/plugin.yml
transmart-notifications/grails-app/services/org/transmart/notifications/QuerySetSubscriptionMailService.groovy

- rename 'application.yml' to 'plugin.yml' according to https://docs.grails.org/3.2.3/guide/plugins.html
- fix configuration formatting
Other plugins of transmart-api-server should be also checked whether they do not require similar modification. It is described in: https://jira.thehyve.nl/browse/TMT-276

Fix notifications plugin config

---

transmart-api-server/build.gradle
transmart-api-server/src/main/groovy/org/transmartproject/api/server/client/OfflineTokenClientRequestFactory.groovy

HttpComponentsClientHttpRequestFactory requires adding
"org.apache.httpcomponents:httpclient:4.5.5" library

Use SimpleClientHttpRequestFactory not to add a dependency on apache.httpclient

---

.travis.yml
CONTRIBUTING.md

https://jira.thehyve.nl/browse/TMT-285

Add transmart-api-server tests to Travis

---

build.gradle
transmart-notifications/README.md
transmart-notifications/grails-app/conf/plugin.yml
transmart-notifications/grails-app/jobs/org/transmart/notifications/QuerySetSubscriptionDailyJob.groovy
transmart-notifications/grails-app/jobs/org/transmart/notifications/QuerySetSubscriptionWeeklyJob.groovy
transmart-notifications/grails-app/services/org/transmart/notifications/QuerySetSubscriptionMailService.groovy

https://jira.thehyve.nl/browse/TMT-294

Change transmart-notifications default configuration, add customizable trigger time

---

transmart-api-server/README.md
transmart-api-server/src/main/groovy/org/transmartproject/api/server/server/SecurityConfig.groovy
transmart-rest-api-e2e/README.md
transmart-rest-api-e2e/src/test/groovy/annotations/RequiresStudyExtension.groovy
transmart-rest-api-e2e/src/test/groovy/annotations/RequiresV1ApiSupport.java
transmart-rest-api-e2e/src/test/groovy/annotations/RequiresV1ApiSupportExtension.groovy
transmart-rest-api-e2e/src/test/groovy/config/Config.groovy
transmart-rest-api-e2e/src/test/groovy/tests/rest/v1/HighDimSpec.groovy
transmart-rest-api-e2e/src/test/groovy/tests/rest/v1/ObservationsSpec.groovy
transmart-rest-api-e2e/src/test/groovy/tests/rest/v1/OntologyTermsSpec.groovy
transmart-rest-api-e2e/src/test/groovy/tests/rest/v1/PatientSetsSpec.groovy
transmart-rest-api-e2e/src/test/groovy/tests/rest/v1/StudySpec.groovy
transmart-rest-api-e2e/src/test/groovy/tests/rest/v1/SubjectsSpec.groovy
transmart-rest-api-e2e/src/test/groovy/tests/rest/v1/V1ApiDisabledSpec.groovy

Covers [TMT-298](https://jira.thehyve.nl/browse/TMT-298) and [TMT-328](https://jira.thehyve.nl/browse/TMT-328)

Disable the "v1" API for transmart-api-server

---

transmart-core-api/src/main/groovy/org/transmartproject/core/ontology/MDStudy.groovy
transmart-core-db-tests/src/integration-test/groovy/org/transmartproject/db/multidimquery/CrossTableSpec.groovy
transmart-core-db/grails-app/services/org/transmartproject/db/clinical/CrossTableService.groovy
transmart-core-db/grails-app/services/org/transmartproject/db/clinical/PatientSetService.groovy
transmart-rest-api/src/func-test/groovy/org/transmartproject/rest/v2/AccessPolicySpec.groovy
transmart-rest-api/src/main/groovy/org/transmartproject/rest/TestResource.groovy
transmart-rest-api/src/main/groovy/org/transmartproject/rest/marshallers/MDStudySerializationHelper.groovy
transmart-rest-api/src/test/groovy/org/transmartproject/test/TestService.groovy

Fixes [TMT-243](https://jira.thehyve.nl/browse/TMT-243).
Includes #275.

 Save patient sets to database when creating cross table.

---

transmart-api-server/build.gradle
transmart-api-server/grails-app/conf/application.yml
transmart-api-server/grails-app/controllers/org/transmartproject/api/server/ApiServerUrlMappings.groovy
transmart-api-server/grails-app/services/org/transmartproject/api/server/StartupService.groovy
transmart-api-server/src/main/groovy/org/transmartproject/api/server/server/SecurityConfig.groovy

Fixes [TMT-314](https://jira.thehyve.nl/browse/TMT-314)

Enable serving of OpenAPI documentation with transmart-api-server.

---

transmart-rest-api-e2e/src/test/groovy/base/RestHelper.groovy
transmart-rest-api-e2e/src/test/groovy/tests/rest/access/AccessCheckSpec.groovy

Covers [TMT-327](https://jira.thehyve.nl/browse/TMT-327)

Add rest api e2e tests for access token validation

---

transmart-api-server/grails-app/conf/logback.groovy

[TMT-293](https://jira.thehyve.nl/browse/TMT-293)
Configuration of logback is similar to the one for transmart-server with the difference that there is a different rolling policy. Instead of size only based, transmart-api will have a time-and-size policy - daily rollover, limited by size size of 100MB. 
There are also 2 optional parameters (currently commented out):
- maxHistory that controls the maximum number of archive files to keep, asynchronously deleting older files.
- totalSizeCap that controls the total size of all archive files.
We can set them if needed.

Change logback configuration of transmart-api-server with production mode

---

transmart-core-db/grails-app/services/org/transmartproject/db/clinical/AggregateDataService.groovy
transmart-core-db/grails-app/services/org/transmartproject/db/tree/TreeCacheService.groovy
transmart-core-db/grails-app/services/org/transmartproject/db/tree/TreeService.groovy

Fixes [TMT-344](https://jira.thehyve.nl/browse/TMT-344).

Use permissions as cache key instead of username.

---

transmart-rest-api/src/main/groovy/org/transmartproject/rest/serialization/tabular/DataTableTSVSerializer.groovy

[TMT-352](https://jira.thehyve.nl/browse/TMT-352)

Prevent writing empty rows to dimensions-data files during TSV export

---

transmart-core-db-tests/src/integration-test/groovy/org/transmartproject/db/userqueries/UserQuerySetServiceSpec.groovy
transmart-core-db/grails-app/services/org/transmartproject/db/userqueries/UserQuerySetService.groovy

Fix generating emails with empty updates for query subscription

---

transmart-core-db-tests/src/integration-test/groovy/org/transmartproject/db/multidimquery/HibernateCriteriaQueryBuilderSpec.groovy
transmart-core-db/src/main/groovy/org/transmartproject/db/multidimquery/query/HibernateCriteriaQueryBuilder.groovy

Fixes [TMT-363](https://jira.thehyve.nl/browse/TMT-363).

Fix the query builder for when a user has no access to any study.

---

open-api/swagger.json
open-api/swagger.yaml
open-api/swagger_spec.js
transmart-core-api/src/main/groovy/org/transmartproject/core/config/RuntimeConfigRepresentation.groovy
transmart-core-api/src/main/groovy/org/transmartproject/core/config/SystemResource.groovy
transmart-core-api/src/main/groovy/org/transmartproject/core/config/UpdateStatus.groovy
transmart-core-api/src/main/groovy/org/transmartproject/core/tree/TreeResource.groovy
transmart-core-api/src/main/groovy/org/transmartproject/core/userquery/UserQuerySetResource.groovy
transmart-core-db-tests/src/integration-test/groovy/org/transmartproject/db/userqueries/UserQuerySetServiceSpec.groovy
transmart-core-db/grails-app/services/org/transmartproject/db/clinical/AggregateDataService.groovy
transmart-core-db/grails-app/services/org/transmartproject/db/support/SystemService.groovy
transmart-core-db/grails-app/services/org/transmartproject/db/tree/TreeService.groovy
transmart-core-db/grails-app/services/org/transmartproject/db/userqueries/UserQuerySetService.groovy
transmart-rest-api/grails-app/controllers/org/transmartproject/rest/ConfigController.groovy
transmart-rest-api/grails-app/controllers/org/transmartproject/rest/RestApiUrlMappings.groovy
transmart-rest-api/grails-app/controllers/org/transmartproject/rest/SystemController.groovy
transmart-rest-api/grails-app/controllers/org/transmartproject/rest/TreeController.groovy
transmart-rest-api/grails-app/controllers/org/transmartproject/rest/UserQuerySetController.groovy
transmart-rest-api/src/func-test/groovy/org/transmartproject/rest/v2/ApiAuditInterceptorSpec.groovy

Fixes [TMT-364](https://jira.thehyve.nl/browse/TMT-364).

Refactor admin endpoints

---

transmart-core-db/grails-app/services/org/transmartproject/db/clinical/PatientSetService.groovy
transmart-rest-api/src/func-test/groovy/org/transmartproject/rest/v2/AccessPolicySpec.groovy

Fixes [TMT-369](https://jira.thehyve.nl/browse/TMT-369).

Include patients for summary-level access in set of all patients.

---

transmart-core-db/grails-app/services/org/transmartproject/db/clinical/MultidimensionalDataResourceService.groovy
transmart-rest-api/src/func-test/groovy/org/transmartproject/rest/v2/AccessPolicySpec.groovy

Fixes [TMT-367](https://jira.thehyve.nl/browse/TMT-367)

Change dimension elements access level

---

transmart-api-server/grails-app/conf/application.yml
transmart-core-db/grails-app/services/org/transmartproject/db/clinical/AggregateDataOptimisationsService.groovy
transmart-core-db/grails-app/services/org/transmartproject/db/clinical/AggregateDataService.groovy
transmart-core-db/grails-app/services/org/transmartproject/db/clinical/CrossTableService.groovy
transmart-core-db/grails-app/services/org/transmartproject/db/clinical/PatientSetService.groovy
transmart-core-db/src/integration-test/groovy/org/transmartproject/db/clinical/AggregateDataOptimisationsServiceSpec.groovy
transmart-core-db/src/integration-test/groovy/org/transmartproject/db/clinical/CrossTableServicePgSpec.groovy
transmart-data/ddl/postgres/biomart_user/views/patient_num_boundaries.sql
transmart-data/ddl/postgres/biomart_user/views/patient_set_bitset.sql
transmart-data/updatedb/release-17.1-HYVE-5/README.md
transmart-data/updatedb/release-17.1-HYVE-5/postgres/Makefile
transmart-data/updatedb/release-17.1-HYVE-5/postgres/migrate_bitset.sql
transmart-rest-api-e2e/src/test/groovy/config/Config.groovy

Fixes [TMT-371](https://jira.thehyve.nl/browse/TMT-371).
To do: document code.

Optimise crosstable

---

transmart-core-db/grails-app/services/org/transmartproject/db/clinical/AggregateDataService.groovy
transmart-core-db/grails-app/services/org/transmartproject/db/support/SystemService.groovy
transmart-core-db/src/integration-test/groovy/org/transmartproject/db/multidimquery/AggregateDataServicePgSpec.groovy
transmart-server/grails-app/conf/ehcache.xml

[TMT-400](https://jira.thehyve.nl/browse/TMT-400)

Apply cache to the counts_per_concept call

---

transmart-data/updatedb/release-17.1-HYVE-5/oracle/to_date_data_type.sql
transmart-data/updatedb/release-17.1-HYVE-5/postgres/to_date_data_type.sql

to update only root (not modifier) observations tracked by concept.

Improve date observation migration scripts

---

transmart-notifications/grails-app/services/org/transmartproject/notifications/QuerySetSubscriptionMailService.groovy

Fix notification plugin settings to properly format the html body of emails

---

transmart-core-db/grails-app/services/org/transmartproject/db/userqueries/UserQuerySetService.groovy

The default map constructors were not working for asynchronous call.
Fixes [TMT-456](https://jira.thehyve.nl/browse/TMT-456)

Fix user query related domain object mapping for async scan

---

open-api/swagger.yaml
transmart-core-api/src/main/groovy/org/transmartproject/core/config/SystemResource.groovy
transmart-core-db/grails-app/services/org/transmartproject/db/clinical/AggregateDataService.groovy
transmart-core-db/grails-app/services/org/transmartproject/db/support/SystemService.groovy
transmart-rest-api/grails-app/controllers/org/transmartproject/rest/RestApiUrlMappings.groovy
transmart-rest-api/grails-app/controllers/org/transmartproject/rest/SystemController.groovy
transmart-rest-api/src/func-test/groovy/org/transmartproject/rest/v2/ApiAuditInterceptorSpec.groovy

Proposal for a single status call for admin update tasks.

Use a single update status endpoint for admin update tasks.

---

transmart-core-api/src/main/groovy/org/transmartproject/core/multidimquery/query/CommonConstraints.groovy
transmart-core-api/src/test/groovy/org/transmartproject/core/multidimquery/query/CommonConstraintsSpec.groovy
transmart-core-db/grails-app/services/org/transmartproject/db/clinical/AggregateDataResourceImplService.groovy
transmart-core-db/grails-app/services/org/transmartproject/db/clinical/CrossTableResourceImpService.groovy
transmart-core-db/src/test/groovy/org/transmartproject/db/clinical/CrossTableResourceImplServiceSpec.groovy

Fixes [TMT-472](https://jira.thehyve.nl/browse/TMT-472).

Fix counts threshold in the cross table for zero counts.

---

transmart-rest-api/grails-app/controllers/org/transmartproject/rest/ExportController.groovy

Fix export controller Json serialisation.

---

transmart-rest-api/grails-app/services/org/transmartproject/rest/dataExport/ExportAsyncJobService.groovy
transmart-rest-api/grails-app/services/org/transmartproject/rest/dataExport/ExportService.groovy
transmart-rest-api/src/main/groovy/org/transmartproject/rest/dataExport/ExportJobExecutor.groovy

Fix export job executor; add @CompileStatic.

---

transmart-core-db/src/main/groovy/org/transmartproject/db/clinical/ConstraintAccessChecker.groovy
transmart-rest-api/src/func-test/groovy/org/transmartproject/rest/v2/AccessPolicySpec.groovy

Error message like "Access denied to concept code: 2cba26058f55a7d579f4a0a1f0b9a2e8d5e149a0" does not say which actually user does not have the access.

Add username to access error log message

---

transmart-core-api/src/main/groovy/org/transmartproject/core/multidimquery/HypercubeValue.groovy
transmart-core-api/src/main/groovy/org/transmartproject/core/multidimquery/datatable/DataTable.groovy
transmart-core-api/src/main/groovy/org/transmartproject/core/multidimquery/datatable/Dimension.groovy
transmart-core-db-tests/src/integration-test/groovy/org/transmartproject/db/dataquery/highdim/assayconstraints/PatientIdListConstraintSpec.groovy
transmart-core-db-tests/src/test/groovy/org/transmartproject/db/support/InQueryTest.groovy
transmart-core-db/grails-app/domain/org/transmartproject/db/i2b2data/Study.groovy
transmart-core-db/grails-app/services/org/transmartproject/db/clinical/SurveyTableColumnService.groovy
transmart-core-db/grails-app/services/org/transmartproject/db/support/InQuery.groovy
transmart-core-db/src/integration-test/groovy/org/transmartproject/db/multidimquery/DataTablePgSpec.groovy
transmart-core-db/src/integration-test/groovy/org/transmartproject/db/multidimquery/DimensionsPgSpec.groovy
transmart-core-db/src/integration-test/groovy/org/transmartproject/db/support/InQuerySpec.groovy
transmart-core-db/src/main/groovy/org/transmartproject/db/dataquery/clinical/AcrossTrialsDataQuery.groovy
transmart-core-db/src/main/groovy/org/transmartproject/db/multidimquery/DimensionImpl.groovy
transmart-data/ddl/postgres/i2b2demodata/study.sql
transmart-rest-api-e2e/src/test/groovy/tests/rest/v2/DataTableSpec.groovy
transmart-rest-api/src/func-test/groovy/org/transmartproject/rest/v2/AccessPolicySpec.groovy
transmart-rest-api/src/main/groovy/org/transmartproject/rest/serialization/DataTableSerializer.groovy

Write only dimension elements of current page of data table.
Includes #357.

Fix data table serialisation

---

transmart-core-db-tests/src/integration-test/groovy/org/transmartproject/db/dataquery/highdim/assayconstraints/PatientIdListConstraintSpec.groovy
transmart-core-db-tests/src/test/groovy/org/transmartproject/db/support/InQueryTest.groovy
transmart-core-db/grails-app/services/org/transmartproject/db/support/InQuery.groovy
transmart-core-db/src/integration-test/groovy/org/transmartproject/db/support/InQuerySpec.groovy
transmart-core-db/src/main/groovy/org/transmartproject/db/dataquery/clinical/AcrossTrialsDataQuery.groovy
transmart-core-db/src/main/groovy/org/transmartproject/db/multidimquery/DimensionImpl.groovy

Possibly fixes [TMT-481](https://jira.thehyve.nl/browse/TMT-481). Need to verify.

Attempt to fix fetching many dimension elements for PostgreSQL.

---

transmart-data/ddl/postgres/GLOBAL/Makefile

replace installation of postgresql-server-dev-all package with installation of packer of certain version taken from pgversion environment variable.

install postgresql-server-dev package with certain version

---

transmart-core-api/src/main/groovy/org/transmartproject/core/ontology/StudyMetadata.groovy
transmart-core-api/src/test/groovy/org/transmartproject/core/ontology/StudyMetadataTests.groovy

Add support of string missing values

---

transmart-rest-api-e2e/src/test/groovy/tests/rest/v2/AggregatesPerConceptSpec.groovy
transmart-rest-api-e2e/src/test/groovy/tests/rest/v2/DataExportSpec.groovy
transmart-rest-api-e2e/src/test/groovy/tests/rest/v2/PatientsSetSpec.groovy
transmart-rest-api-e2e/src/test/groovy/tests/rest/v2/PatientsSpec.groovy
transmart-rest-api-e2e/src/test/groovy/tests/rest/v2/RelationSpec.groovy
transmart-rest-api-e2e/src/test/groovy/tests/rest/v2/hypercube/AccessLevelSpec.groovy
transmart-rest-api/grails-app/controllers/org/transmartproject/rest/QueryController.groovy

HighDimSpec and TranscriptLevelRnaSeqSpec are still failing for me with following error message: 
```
Could not resolve view with name '/query/observations' in servlet with name 'grailsDispatcherServlet'
```

Fix some e2e tests

---

transmart-data/build.gradle
transmart-data/test_studies/CSR/i2b2metadata/i2b2_secure.tsv

includes missing parts of https://github.com/thehyve/transmart-core/pull/382

Include test studies to ts data distribution

---

transmart-core-api/src/main/groovy/org/transmartproject/core/multidimquery/query/NormaliseConstraintRewriter.groovy
transmart-core-db/src/test/groovy/org/transmartproject/db/multidimquery/QueryRewriterSpec.groovy

Fixes [TMT-772](https://jira.thehyve.nl/browse/TMT-772)

Fix normalization of disjunction with true constraint

---

docs/README.md

Update installation instruction for 17.1-HYVE-5.9-RC1

---

docker/README.md
docker/docker-compose.yml
docker/transmart-api-server/Dockerfile
docker/transmart-api-server/docker-entrypoint.sh

Image uploaded to [Docker Hub](https://hub.docker.com/r/thehyve/transmart-api-server).
Fixes thehyve/glowing-bear-docker#3.

Update version in Docker file; updated Docker documentation.

---

transmart-rest-api/grails-app/services/org/transmartproject/rest/dataExport/ExportAsyncJobService.groovy
transmart-rest-api/src/test/groovy/org/transmartproject/rest/dataExport/ExportAsyncJobServiceSpec.groovy

Escape invalid file name characters in export names

---

docker/transmart-api-server/logback.groovy

Fixes https://github.com/thehyve/glowing-bear-docker/issues/14

Change the log level of apache cache logs to ERROR

---

transmart-schemas/src/main/resources/db/changelog/changes/20190625151656_create_pg_bitcount_extension.xml
transmart-schemas/src/main/resources/db/changelog/db.changelog-master.yaml

Solves: [TMT-920](https://jira.thehyve.nl/browse/TMT-920)

Add auto-creating of pg_bitcount extension (if available) to liquibase scripts

---

transmart-schemas/src/main/resources/db/changelog/changes/20190625151656_create_pg_bitcount_extension.xml
transmart-schemas/src/main/resources/db/changelog/changes/20191907041159_biomart_user_views.xml
transmart-schemas/src/main/resources/db/changelog/db.changelog-master.yaml

recreated pull-request with squeshed commits

A biomart_user views with bitset

---

open-api/swagger.yaml
transmart-core-api/src/main/groovy/org/transmartproject/core/multidimquery/hypercube/Dimension.groovy
transmart-core-api/src/main/groovy/org/transmartproject/core/multidimquery/hypercube/DimensionProperties.groovy
transmart-core-db/src/main/groovy/org/transmartproject/db/multidimquery/DimensionImpl.groovy
transmart-rest-api/src/main/groovy/org/transmartproject/rest/serialization/HypercubeJsonSerializer.groovy

Related ticket: [TMT-932](https://jira.thehyve.nl/browse/TMT-932)

Extend dimension properties to include modifier codes

---

open-api/swagger.yaml
transmart-core-api/src/main/groovy/org/transmartproject/core/pedigree/Relation.groovy
transmart-core-api/src/main/groovy/org/transmartproject/core/pedigree/RelationRepresentation.groovy
transmart-core-api/src/main/groovy/org/transmartproject/core/pedigree/RelationResource.groovy
transmart-core-db/grails-app/domain/org/transmartproject/db/pedigree/Relation.groovy
transmart-core-db/grails-app/services/org/transmartproject/db/ontology/MDStudiesService.groovy
transmart-core-db/grails-app/services/org/transmartproject/db/pedigree/RelationService.groovy
transmart-core-db/src/integration-test/groovy/org/transmartproject/db/pedigree/RelationSpec.groovy
transmart-core-db/src/integration-test/groovy/org/transmartproject/db/pedigree/RelationTypeSpec.groovy
transmart-rest-api-e2e/src/test/groovy/tests/rest/v2/RelationSpec.groovy
transmart-rest-api/grails-app/controllers/org/transmartproject/rest/RelationController.groovy
transmart-rest-api/grails-app/controllers/org/transmartproject/rest/RestApiUrlMappings.groovy

Related ticket: [TMT-934](https://jira.thehyve.nl/browse/TMT-934)

Add relations endpoint

---

transmart-core-db/grails-app/services/org/transmartproject/db/clinical/AggregateDataOptimisationsService.groovy

The query would fail on databases populated using Liquibase.
Fixes [TMT-962](https://jira.thehyve.nl/browse/TMT-962).

Fix optimised cross table query by adding schema to view.

---

open-api/swagger.yaml
transmart-api-server/grails-app/conf/application.yml
transmart-api-server/grails-app/init/org/transmartproject/api/server/Application.groovy
transmart-api-server/src/main/groovy/org/transmartproject/api/server/server/SecurityConfig.groovy

Add `/health` endpoint to monitor availability of the application.
Related ticket: [TMT-944]( https://jira.thehyve.nl/browse/TMT-944)

Include Health Check Indicators for application status monitoring

---

docker/docker-compose.yml
docker/transmart-api-server/docker-entrypoint.sh
docs/README.md
transmart-api-server/README.md
transmart-api-server/grails-app/conf/application.yml
transmart-api-server/src/main/groovy/org/transmartproject/api/server/server/SecurityConfig.groovy
transmart-api-server/src/main/groovy/org/transmartproject/api/server/server/TransmartAuthenticationException.groovy
transmart-api-server/src/main/groovy/org/transmartproject/api/server/server/TransmartKeycloakAuthenticationProcessingFilter.groovy
transmart-api-server/src/main/groovy/org/transmartproject/api/server/user/AccessLevels.groovy
transmart-api-server/src/main/groovy/org/transmartproject/api/server/user/KeycloakUserResourceService.groovy
transmart-api-server/src/test/groovy/org/transmartproject/api/server/user/AccessLevelsSpec.groovy
transmart-api-server/src/test/groovy/org/transmartproject/api/server/user/KeycloakUserResourceServiceSpec.groovy
transmart-schemas/README.md

Same as #451, but to correct branch (`dev`).

Deny users without roles

---

transmart-core-db/grails-app/services/org/transmartproject/db/tree/TreeCacheService.groovy
transmart-core-db/src/main/groovy/org/transmartproject/db/tree/TreeNodeConstraintHelper.groovy

Expose intermediate concept nodes in tree_nodes endpoint.

---

docker/transmart-api-server/docker-entrypoint.sh

Fixes #472
I still need to test this! Will update the PR once I got the chance to test this.

Made BIOMART_PASSWORD configurable

---

.travis.yml
.travis/docker_release.sh
.travis/notify.sh
.travis/settings.xml
build.gradle
docker/README.md
docker/transmart-api-server/Dockerfile
docker/transmart-api-server/README.md
docker/transmart-api-server/docker-entrypoint.sh
gradle.properties
transmart-api-server/src/main/groovy/org/transmartproject/api/server/user/AccessLevels.groovy
transmart-core-db/grails-app/conf/application.yml
transmart-data/env/vars-ubuntu.php
transmart-rest-api/src/main/groovy/org/transmartproject/rest/protobuf/HighDimBuilder.groovy
transmart-schemas/src/main/resources/db/changelog/changes/20200210135535_autoincrement_id_columns.xml
transmart-schemas/src/main/resources/db/changelog/db.changelog-master.yaml

- Upgrade Grails version to 3.2.13.
- Release transmart-core to Nexus, Docker Hub from Travis.

Grails upgrade; publish releases from Travis

---

transmart-core-db-tests/src/integration-test/groovy/org/transmartproject/db/multidimquery/QueryServiceSpec.groovy
transmart-core-db-tests/src/main/groovy/org/transmartproject/db/dataquery/clinical/ClinicalTestData.groovy
transmart-core-db/grails-app/domain/org/transmartproject/db/i2b2data/Study.groovy
transmart-core-db/grails-app/domain/org/transmartproject/db/i2b2data/TrialVisit.groovy
transmart-core-db/src/integration-test/groovy/org/transmartproject/db/multidimquery/QueryServicePgSpec.groovy
transmart-core-db/src/integration-test/groovy/org/transmartproject/db/multidimquery/SurveyTableViewSpec.groovy
transmart-core-db/src/main/groovy/org/transmartproject/db/multidimquery/DimensionImpl.groovy
transmart-data/test_studies/MULTI-DWH/i2b2demodata/observation_fact.tsv
transmart-rest-api/src/func-test/groovy/org/transmartproject/rest/data/AccessPolicyTestData.groovy

Fix the join table mapping for the study-trial visit relation.

---

build.gradle
transmart-core-db/grails-app/services/org/transmartproject/db/clinical/AggregateDataOptimisationsService.groovy

Clean up connection after refreshing materialised view.
