thehyve/transmart-core

- transmartApp/grails-app/conf/application.groovy
We have two types of configurations: internal and external.
Internal configuration is part of application.
The source code of it can be found here `transmartApp/grail-app/conf/application.groovy`.
External configuration files (`Config.groovy`, `DataSource.groovy` as legacy way or `application.groovy`) are located under `~/.grails/transmartConfig/` directory.
Where `~` is a home directory of the user who runs the application.
The order of applying these configuration files as follows:
internal `application.groovy`
externals
`Config.groovy`
`DataSource.groovy`
`application.groovy`
The configuration file that goes later could override settings set by previous ones.
It becomes harder to reason about such overrides when there is logic that depends on the flags in the configuration files.
> Remove gwas conditional initialization from internal config.

- open-api/README.md
- open-api/swagger.json
- open-api/swagger.yaml
- open-api/swagger_spec.js
- transmart-rest-api/grails-app/controllers/org/transmartproject/rest/PatientQueryController.groovy
+ small fix for displayed api version in 'POST /v2/patient_Set' result
> Add missing GET /v2/patient_sets/{resultInstanceId} call description to swagger doc

- open-api/swagger.yaml
- transmart-core-api/src/main/groovy/org/transmartproject/core/multidimquery/AggregateType.groovy
- transmart-core-api/src/main/groovy/org/transmartproject/core/multidimquery/MultiDimensionalDataResource.groovy
- transmart-core-db-tests/src/integration-test/groovy/org/transmartproject/db/multidimquery/QueryServiceSpec.groovy
- transmart-core-db/grails-app/domain/org/transmartproject/db/i2b2data/ObservationFact.groovy
- transmart-core-db/grails-app/services/org/transmartproject/db/clinical/MultidimensionalDataResourceService.groovy
- transmart-core-db/src/main/groovy/org/transmartproject/db/util/GormWorkarounds.groovy
- transmart-core-db/src/main/groovy/org/transmartproject/db/util/ScrollableResultsIterator.groovy
- transmart-rest-api/grails-app/controllers/org/transmartproject/rest/AbstractQueryController.groovy
- transmart-rest-api/grails-app/controllers/org/transmartproject/rest/PatientQueryController.groovy
- transmart-rest-api/grails-app/controllers/org/transmartproject/rest/QueryController.groovy
- transmart-rest-api/grails-app/controllers/org/transmartproject/rest/VersionController.groovy
- transmart-rest-api/grails-app/services/org/transmartproject/rest/MultidimensionalDataService.groovy
- transmart-rest-api/src/main/groovy/org/transmartproject/rest/marshallers/QueryResultSerializationHelper.groovy
- transmart-rest-api/src/main/groovy/org/transmartproject/rest/marshallers/QueryResultWrapper.groovy
Add a 'values' aggregate that finds the distinct values in a categorical variable
bonus:
- Only do sanity checks if the main aggregate query fails, that saves us 2-3 (possibly expensive) database queries
- Allow multiple aggregates in a single request, that is much more efficient if the query takes a long time
- remove AggregateType.NONE which we don't need
Closes GDB-47
> Categorical values aggregate

- .travis.yml
- transmart-batch/src/test-func/groovy/org/transmartproject/batch/highdim/cnv/data/CnvDataCleanScenarioTests.groovy
- transmart-core-db-tests/grails-app/conf/application.yml
- Disable the failing tests in `transmart-batch` (`CnvDataCleanScenarioTests`)
I also tried running on the newer Travis image (`trusty`, which is Ubuntu 14.04 instead of 12.04), but there a test in `transmart-core-db-tests` fails (`StudyImplSpec`). See logs in this [gist](https://gist.github.com/gijskant/795be1eb09ab3663078eec2763950c82).
All tests run fine on my own machine. It seems that our tests are quite sensitive to the environment in which they are run. Perhaps we can experiment further with different toolset versions.
Some comparison with versions:
- Travis default:
- Ubuntu 12.04
- Linux 3.13.0
- Oracle JDK 1.8.0_121
- Gradle 2.2.1 with Groovy 2.3.6
- Groovy 1.8.6
- Travis trusty:
- Ubuntu 14.04
- Linux 4.4.0
- Oracle JDK 1.8.0_111
- Gradle 2.13 with Groovy 2.4.4
- Groovy 2.4.5
- …
> Fix travis build

- transmart-batch/transmart-batch.sh
Fix the bash script to run transmart-batch to:
- Correctly run from other locations than the source directory
- Work on non-linux machines (not rely on the `realpath` command).
> Update shell script for transmart-batch.

- transmartApp/grails-app/views/oauthAdmin/edit.gsp
Entered client secret should be BCrypt Hash encrypted
The remark should be there until we resolve a bug related to encrypting clientSecret in Client.groovy domain class.
[Client.groovy#L68](https://github.com/thehyve/transmart-core/blob/lodz2-dev/transmartApp/grails-app/domain/org/transmart/oauth2/Client.groovy#L68)
> Add a remark to "Edit client application" admin page

- transmart-core-db/grails-app/services/org/transmartproject/db/clinical/MultidimensionalDataResourceService.groovy
- transmart-core-db/grails-app/services/org/transmartproject/db/querytool/QueriesResourceService.groovy
- transmart-rest-api/src/integration-test/groovy/org/transmartproject/rest/PatientSetResourceTests.groovy
- transmartApp/grails-app/controllers/org/transmartproject/app/SubsetController.groovy
Implements GDB-71
Save only the user given resultInstanceId description
Instead of having a description of "Patient set for \"${name}\"", we just use `name` as description. The resultInstance.description does not appear to be used anywhere except in the rest api. TransmartApp uses the queryMaster.name property which contains the same name but without the "Patient set for" wrapping. This makes the query master name and the result instance description be identical.
> Patientsetdescription

- transmart-batch/src/main/groovy/org/transmartproject/batch/concept/ConceptFragment.groovy
- transmart-batch/src/test/groovy/org/transmartproject/batch/concept/ConceptPathTests.groovy
This change was already merged in [thehyve/transmart-batch](https://github.com/thehyve/transmart-batch). I propose to also have it here, as some concept names can require to have a `+` in the name.
> Allow escaping of + and _ with a backslash in column mapping file

- transmart-batch/src/main/groovy/org/transmartproject/batch/highdim/datastd/FilterNaNsItemProcessor.groovy
Double.isNaN() throws an exception when the input parameter is null
> Fix for null item values

- transmart-batch/src/main/groovy/org/transmartproject/batch/concept/ConceptTree.groovy
Generating a missing parent node (a new row in the i2b2 table) was
possible only for categorical variables. Extended for other concept
types.
Fix for NOS-3: Numerical variables do not show up in the tree.
> Fix generating tree node entries for non-categorical variables

- transmart-batch/src/main/groovy/org/transmartproject/batch/clinical/facts/ClinicalFactsRowSetFactory.groovy
transmart-batch failed to dynamically create concept paths (i.e. when DATALABEL is used as placeholder in the Category Code column of the column mapping).
Only first concept was created were and all the other values were mapped to the same concept.
> Fix Concept Path Templating for transmart-batch

- transmart-core-api/src/main/groovy/org/transmartproject/core/multidimquery/MultiDimConstraint.groovy
- transmart-core-db/grails-app/services/org/transmartproject/db/clinical/MultidimensionalDataResourceService.groovy
- transmart-core-db/src/main/groovy/org/transmartproject/db/multidimquery/query/Constraint.groovy
Use custom method name instead of overriding toString() as subclasses tend to chenge it often in a way that does not hold uniqueness garantee.
> Fix cache key generation for constraints.

- transmart-server/build.gradle
The current path `src/main/resources/dataExportRScripts` doesn't exist. The folder is however available in transmartApp. Should we update the path to transmartApp or move the scripts at the specified location?
> Update dependency path to dataExportRScripts

- transmart-rest-api/src/main/groovy/org/transmartproject/rest/serialization/HypercubeJsonSerializer.groovy
Some syntactic changes to avoid slow Groovy constructs:
- Avoid hot closures, replace by java-style loops
- change conversions into casts
- Remove the (unneeded) PrintWriter, buffer the Writer instead of the OutputStream and use a larger buffer
I didn't change non-hot groovy style loops in the dimensions for which the equivalent java-style code is cumbersome
I removed the flush() as it negates the use of larger buffers
I have not profiled these optimisations, but this is very likely to help.
> Optimize HypercubeJsonSerializer

- transmart-core-api/src/main/groovy/org/transmartproject/core/multidimquery/MultiDimensionalDataResource.groovy
- transmart-core-db/grails-app/services/org/transmartproject/db/clinical/MultidimensionalDataResourceService.groovy
- transmart-core-db/grails-app/services/org/transmartproject/db/tree/TreeCacheService.groovy
- transmart-core-db/grails-app/services/org/transmartproject/db/tree/TreeService.groovy
- transmart-core-db/src/main/groovy/org/transmartproject/db/util/SharedLock.groovy
- transmart-rest-api/grails-app/controllers/org/transmartproject/rest/QueryController.groovy
- Move shared lock to separate class;
- Fix issues with missing session in task thread;
- Fix tree nodes cache key;
- Change precompute logic to reuse counts per concept across users;
- Also precompute observation and patient counts.
> Refactor cache rebuild

- transmart-copy/src/main/groovy/org/transmartproject/copy/Database.groovy
- transmart-copy/src/main/groovy/org/transmartproject/copy/Util.groovy
- transmart-copy/src/main/groovy/org/transmartproject/copy/table/Observations.groovy
- transmart-copy/src/main/groovy/org/transmartproject/copy/table/Relations.groovy
There were 2 similar utils methods. One of them (removed) did not convert blank string to null.
> Remove code duplication.

- transmart-core-db/grails-app/services/org/transmartproject/db/clinical/MultidimensionalDataResourceService.groovy
Return back one query to get counts per study and concept. Introduce cache for the counts.
> Counts per study per concept master

- open-api/swagger.json
- open-api/swagger.yaml
- open-api/swagger_spec.js
- transmart-core-db/src/main/groovy/org/transmartproject/db/multidimquery/query/CombinationConstraintRewriter.groovy
- transmart-core-db/src/main/groovy/org/transmartproject/db/multidimquery/query/ConstraintSerialiser.groovy
- transmart-core-db/src/main/groovy/org/transmartproject/db/tree/TreeNodeConstraintHelper.groovy
- transmart-core-db/src/test/groovy/org/transmartproject/db/multidimquery/ConstraintSerialiserSpec.groovy
- transmart-core-db/src/test/groovy/org/transmartproject/db/multidimquery/QueryRewriterSpec.groovy
- transmart-rest-api/grails-app/controllers/org/transmartproject/rest/TreeController.groovy
- transmart-rest-api/src/main/groovy/org/transmartproject/rest/marshallers/TreeNodeMarshaller.groovy
- transmart-rest-api/src/main/groovy/org/transmartproject/rest/serialization/TreeJsonSerializer.groovy
- transmart-rest-api/src/test/groovy/org/transmartproject/rest/serialization/TreeJsonSerializerSpec.groovy
Because of a Groovy bug, sometimes the static field of a superclass
is used instead of the static field in the subclass. This caused
'and' constraints to be serialised as 'combination' constraints.
> Fix serialisation of constraints on tree nodes; added tests.

- transmart-server/build.gradle
- transmart-server/grails-app/init/org/transmart/server/Application.groovy
- Add a `pathingJar` for transmart-server to deal with long classpaths
- Replace backslashes in `user.home` system property with forward slashes so it can be used as part of a URI
> Fix issues related to running on Windows

- transmart-batch/src/main/groovy/org/transmartproject/batch/gwas/metadata/GwasMetadataEntry.groovy
When using transmart-batch to load a GWAS dataset with an actual value for the pvalue_cutoff in the metadata file, it results in an error: `ERROR: column "pvalue_cutoff" is of type double precision but expression is of type character varying`
Proposed solution: Change the type of the pvalue_cutoff value to a BigDecimal.
The loading then runs without errors and the pvalue_cutoff value is loaded in the pvalue_cutoff column of biomart.bio_assay_analysis. (Tested with Postgres and the MAGIC dataset with a change in the metadata file to include a pvalue_cutoff value)
> Fix for transmart-batch to be able to load GWAS pvalue_cutoff metadata value

- transmart-batch/src/main/groovy/org/transmartproject/batch/gwas/analysisdata/AssayAnalysisGwasWriter.groovy
- transmart-batch/src/main/groovy/org/transmartproject/batch/gwas/analysisdata/GwasAnalysisRow.groovy
- transmart-batch/src/main/groovy/org/transmartproject/batch/gwas/analysisdata/UpdateGwasTop500Tasklet.groovy
When loading GWAS data with transmart-batch: the values for alleles, standard_error and beta are not loaded in the corresponding columns in the database (biomart.bio_assay_analysis_gwas) and thus are not visible in the GWAS interface.
Proposed solution: update insert statement to include these columns
Tested with Postgres and the MAGIC dataset for which we have alleles and standard_error.
> Fix mapping of extra GWAS columns in transmart-batch

- transmart-core-db/grails-app/services/org/transmartproject/db/support/SystemService.groovy
- transmart-server/grails-app/conf/application.groovy
Number of workers and chunk size (number of patients for
a subtask) can now be configured from application.groovy.
> Add parallelisation parameters to application config.

- transmart-batch/docs/data_formats/gwas.md
- transmart-batch/src/main/groovy/org/transmartproject/batch/gwas/GwasParameterModule.groovy
- transmart-batch/src/main/groovy/org/transmartproject/batch/gwas/metadata/GwasMetadataEntry.groovy
- transmart-gwas-plugin/grails-app/services/com/recomdata/grails/plugin/gwas/RegionSearchService.groovy
- transmart-gwas-plugin/grails-app/views/GWAS/_regionFilter.gsp
The GWAS module currently supports only version 18 and 19 of the human genome build. In order to support the newer 38 version, two changes are needed:
1. update transmart-batch to support load of GWAS datasets using hg38
2. update GWAS plugin to be able to query GWAS datasets using hg38 (relying on an extra config param in Config.groovy if hg38 is to be used per default `com.recomdata.gwas.usehg38table = true`)
> Add support for hg38 in GWAS module

- transmart-rest-api-e2e/src/test/groovy/config/Config.groovy
- transmart-rest-api-e2e/src/test/groovy/tests/rest/v2/DataExportSpec.groovy
- transmart-rest-api/src/main/groovy/org/transmartproject/rest/serialization/tabular/TabularResultSPSSSerializer.groovy
- transmart-rest-api/src/main/groovy/org/transmartproject/rest/serialization/tabular/TabularResultTSVSerializer.groovy
- Write tsv header only once.
- Protect the simple date format object from multiple threads using at the same time.
- Add e2e test for data export of big study.
- Remove e2e assertion that's only true when you run applicaton in dev mode.
> Fix data export serializers.

- open-api/swagger.json
- open-api/swagger.yaml
- open-api/swagger_spec.js
- transmart-rest-api/grails-app/controllers/org/transmartproject/rest/DimensionController.groovy
- transmart-rest-api/grails-app/controllers/org/transmartproject/rest/RestApiUrlMappings.groovy
This call accepts 'constraints' param, which can be longer, so it makes
sense to support POST here.
> Add support for POST to /v2/dimensions/$dimensionName/elements endpoint

- transmart-rest-api/grails-app/services/org/transmartproject/rest/DataTableViewDataSerializationService.groovy
- transmart-rest-api/grails-app/services/org/transmartproject/rest/SurveyTableViewDataSerializationService.groovy
- transmart-rest-api/grails-app/services/org/transmartproject/rest/dataExport/ExportService.groovy
- transmart-rest-api/src/integration-test/groovy/org/transmartproject/rest/DataTableViewDataSerializationServiceSpec.groovy
- transmart-rest-api/src/main/groovy/org/transmartproject/rest/dataExport/ExportJobExecutor.groovy
- transmart-rest-api/src/main/groovy/org/transmartproject/rest/serialization/tabular/AbstractTSVSerializer.groovy
- transmart-rest-api/src/main/groovy/org/transmartproject/rest/serialization/tabular/TabularResultSPSSSerializer.groovy
- transmart-rest-api/src/main/groovy/org/transmartproject/rest/serialization/tabular/TabularResultTSVSerializer.groovy
- transmart-rest-api/src/test/groovy/org/transmartproject/rest/serialization/tabular/TabularResultTSVSerializerSpec.groovy
Fix TMT-210
Using FileOutputStream instead of ZipOutputStream in the
ExportJobExecutor was introduced in this commit:
https://github.com/thehyve/transmart-
core/commit/54766f9c9f9f2063c2c8472cbb97f18666e3afc3
This caused issues with closing the ZipOutputStream. The stream has to
be closed not only after the export job is done, but also when there are
some errors or job is interupted on purpose. This is problematic when
the FileOutputStream is wrapped in ZipOutputStream somewhere else than
ExportJobExecutor. Reverting the change was the easiest solution.
> Revert accepting an OutputStream instead of ZipOutputStream

- transmart-data/ddl/postgres/biomart_user/_cross.sql
- transmart-data/ddl/postgres/biomart_user/functions/scale_bitset.sql
- transmart-data/ddl/postgres/biomart_user/views/patient_num_boundaries.sql
- transmart-data/updatedb/release-17.1-HYVE-4/postgres/migrate.sql
use bit_cat instead lpad to form a bit string with a sufficient number of digits.
> ERROR:  requested length too large

- transmart-rest-api/src/test/groovy/org/transmartproject/rest/logging/ChildProcessAppenderTests.groovy
@gijskant @forus There is one rest-api test for ChildProcessAppender (I kept it from a previous implementation that was using log4j specific libraries) that is failing randomly on dev (Travis). I am not sure why, because it is passing locally and was passing for the PR on Travis: https://github.com/thehyve/transmart-core/pull/247. Started failing after merge of this PR. I restarted rest-api tests couple of times and it is passing again. I need some time to investigate it, so as not to break future builds I would like to temporarily ignore it until I fix it.
> Temporarily ignore randomly failing ChildProcessAppender test

- .travis.yml
- transmart-data/ddl/postgres/GLOBAL/Makefile
When installing on another PostgreSQL database than the
system default, the proper pg_config binary should be
configured.
> Fix build of pg_bitcount on Travis.

- transmart-core-db/grails-app/services/org/transmartproject/db/support/SystemService.groovy
- transmart-core-db/grails-app/services/org/transmartproject/db/userqueries/UserQuerySetService.groovy
- transmart-rest-api/grails-app/controllers/org/transmartproject/rest/PatientQueryController.groovy
- transmart-rest-api/src/func-test/groovy/org/transmartproject/rest/v2/ApiAuditInterceptorSpec.groovy
Got this error:
```
Aug 01 15:58:59 transmart-luke-xl start[21557]: 2018-08-01 15:58:59.642 ERROR --- [nio-8080-exec-3] o.t.interceptors.ApiAuditInterceptor     : Cannot read body for request /v2/patient_sets?name=temp&reuse=true: getReader() has already been called for this request
Aug 01 15:58:59 transmart-luke-xl start[21557]: Try to use request.inputStream instead of request.reader.
Aug 01 15:58:59 transmart-luke-xl start[21557]: 2018-08-01 15:58:59.644 TRACE --- [nio-8080-exec-3] o.t.db.log.AccessLogService              : {"username":"1ca384fd-4bb3-40f4-a88e-2330b2568d7d","event":"patientQuery request","eventMessage":"{\"ip\":\"91.206.81.2\",\"action\":\"createPatientSet\",\"duration\":22,\"status\":201}","requestURL":"/v2/patient_sets?name=temp&reuse=true","accessTime":"2018-08-01T15 …
```
> Fix audit logging for patient set creation.

- open-api/swagger.json
- open-api/swagger.yaml
- open-api/swagger_spec.js
- transmart-core-api/src/main/groovy/org/transmartproject/core/multidimquery/PatientSetResource.groovy
- transmart-core-db-tests/src/integration-test/groovy/org/transmartproject/db/multidimquery/QueryServiceSpec.groovy
- transmart-core-db/grails-app/services/org/transmartproject/db/clinical/AggregateDataService.groovy
- transmart-core-db/grails-app/services/org/transmartproject/db/clinical/PatientSetService.groovy
- transmart-core-db/grails-app/services/org/transmartproject/db/support/SystemService.groovy
- transmart-core-db/src/integration-test/groovy/org/transmartproject/db/multidimquery/QueryServicePgSpec.groovy
- transmart-data/ddl/postgres/i2b2demodata/qt_query_master.sql
- transmart-data/updatedb/release-17.1-HYVE-5/postgres/migrate_bitset.sql
- Don't use database field for that. Doesn't work for oracle as it has clob that you could not apply indexes on. Use the application cache instead.
- Don't reuse query master objects at all.
> Use application cache to reuse patient sets.

- transmart-rest-api-e2e/src/test/groovy/tests/rest/v2/DataTableSpec.groovy
Test data loaded to Oracle db via groovy loading script does not always have 5 digits, see https://jira.thehyve.nl/browse/TMT-402
> Change 'export data table with a modifier dimension' e2e test assertion

- transmart-core-db/grails-app/services/org/transmartproject/db/clinical/AggregateDataService.groovy
- transmart-core-db/grails-app/services/org/transmartproject/db/tree/TreeService.groovy
- transmart-rest-api-e2e/src/test/groovy/config/Config.groovy
- transmart-rest-api-e2e/src/test/groovy/tests/rest/v2/SystemAdminSpec.groovy
it happened for admin users that had no permission specified.
It apeared that `rebuildCountsPerStudyAndConceptCache`
did double work. `rebuildCountsCacheForUser` pre-cached
counts already. Removing it seems like right solution.
Fixes https://jira.thehyve.nl/browse/TMT-435
> Fix after data loading call empties s.&.c. counts

- transmart-copy/src/main/groovy/org/transmartproject/copy/Copy.groovy
This enables uploading patient relation data without having a study table. The patient relation tables are truncated and the information is not associated with any study.
> Do not attempt study deletion when using pedigree mode. 

- transmart-api-server/README.md
- transmart-api-server/grails-app/conf/logback.groovy
- transmart-rest-api/src/main/groovy/org/transmartproject/rest/logging/ApiAuditLogJsonLayout.groovy
- transmart-rest-api/src/main/groovy/org/transmartproject/rest/logging/ChildProcessAppender.groovy
Previously, an error message would be written to stdout:
```
LOGBACK: No context given for ch.qos.logback.contrib.json.classic.JsonLayout@...
```
> Logging configuration update.

- open-api/swagger.yaml
- transmart-api-server/src/main/groovy/org/transmartproject/api/server/server/SecurityConfig.groovy
- transmart-core-db/grails-app/services/org/transmartproject/db/clinical/AggregateDataService.groovy
- transmart-core-db/grails-app/services/org/transmartproject/db/support/ParallelPatientSetTaskService.groovy
- transmart-core-db/grails-app/services/org/transmartproject/db/support/SystemService.groovy
- transmart-core-db/src/integration-test/groovy/org/transmartproject/db/multidimquery/ParallelAggregateDataServicePgSpec.groovy
- transmart-core-db/src/main/groovy/org/transmartproject/db/TransmartCoreGrailsPlugin.groovy
- transmart-core-db/src/main/groovy/org/transmartproject/db/config/RuntimeConfigImpl.groovy
- transmart-core-db/src/main/groovy/org/transmartproject/db/config/SystemConfig.groovy
The system would spawn a new pool of threads for each request/operation (e.g., per export or per counts request) instead of having one pool for the entire system. This caused problems with the number of database connections.
> Fix worker pool for parallel tasks to one per system.

- docs/README.md
- open-api/README.md
The validation badge is hidden, because http://online.swagger.io does not support opeapi 3 validation
> Add minor documentation updates

- transmart-rest-api/src/main/groovy/org/transmartproject/rest/serialization/tabular/TabularResultSPSSSerializer.groovy
- transmart-rest-api/src/test/groovy/org/transmartproject/rest/serialization/tabular/TabularResultSPSSSerializerSpec.groovy
New line characters in strings fields, even surrounded by qualifier, always separate fields and invalid .sav files are produced.
> Remove new line character from string fields in spss export

- transmart-core-api/src/main/groovy/org/transmartproject/core/querytool/QueryResultSummary.groovy
- transmart-core-db/grails-app/services/org/transmartproject/db/clinical/AggregateDataResourceImplService.groovy
- transmart-core-db/grails-app/services/org/transmartproject/db/clinical/PatientSetService.groovy
- transmart-rest-api/src/func-test/groovy/org/transmartproject/rest/v2/AccessPolicySpec.groovy
Users with count with threshold level of access
should not see original size of the patient set
> Check access on patient set size

- transmart-core-db/src/integration-test/groovy/org/transmartproject/db/multidimquery/QueryServicePgSpec.groovy
- transmart-core-db/src/integration-test/groovy/org/transmartproject/db/multidimquery/SurveyTableViewSpec.groovy
- transmart-rest-api/src/main/groovy/org/transmartproject/rest/serialization/tabular/TabularResultSPSSSerializer.groovy
- transmart-rest-api/src/test/groovy/org/transmartproject/rest/serialization/tabular/TabularResultSPSSSerializerSpec.groovy
It used 1-12h format without am/pm specification.
Use 0-23h datetime format for intermediate tsv export instead.
Java date format:
hh - 1-12
HH - 0-23
See TMT-648 for more details.
> Fix afternoon time for spss export

- .travis.yml
- transmart-api-server/src/main/groovy/org/transmartproject/api/server/server/SecurityConfig.groovy
- transmart-batch/build.gradle
- transmart-batch/src/main/groovy/org/transmartproject/batch/clinical/ontology/InsertOntologyTreeTasklet.groovy
- transmart-batch/src/main/groovy/org/transmartproject/batch/concept/InsertConceptsService.groovy
- transmart-batch/src/main/groovy/org/transmartproject/batch/ontologymapping/WriteOntologyMappingTasklet.groovy
- transmart-copy/build.gradle
Fixes TMT-658
When the security context is shared the authentification field gets mutated by multiple concurrent requests causing all sort of issues. Each request starts with setting authentification field with unauthenticated bean first and only after analyzing the token with authenticated.
The PR makes each request to use own security context instance.
The http session instance still could be shared between http requests when jsessionid is supplied in the cookie header.
TMT-664 is a ticket to asses how harmless it that.
> Stop sharing security context between http sessions

- transmart-copy/src/main/groovy/org/transmartproject/copy/Counter.groovy
- transmart-copy/src/main/groovy/org/transmartproject/copy/table/Observations.groovy
I noticed that on the command line, transmart copy always reports `[INFO] 1 batches of 500 inserted.`. This change fixes the reporting of number of batches.
> Fix the batch count in transmart-copy.

- transmart-notifications/grails-app/jobs/org/transmartproject/notifications/QuerySetSubscriptionDailyJob.groovy
- transmart-notifications/grails-app/jobs/org/transmartproject/notifications/QuerySetSubscriptionWeeklyJob.groovy
- transmart-notifications/src/main/groovy/org/transmartproject/notifications/TransmartNotificationsGrailsPlugin.groovy
Value of `Holders.config.org.transmartproject.notifications.enabled` was not properly resolved inside subscription job classes.
> Fix disabling of notifications quartz jobs

- docker/README.md
- docker/docker-compose.yml
- docker/transmart-api-server/docker-entrypoint.sh
Expect `https://keycloak-example.com` (without `/auth` part)
> Expect the same KEYCLOAK_SERVER_URL in all glowing-bear-docker components

- open-api/swagger.yaml
- transmart-core-db/grails-app/services/org/transmartproject/db/support/SystemService.groovy
Run scan and cache rebuild tasks only if the offline token is specified in the configuration.
Fixes [TMT-825](https://jira.thehyve.nl/browse/TMT-825).
There is still an issue when running after_data_loading_update and when the database was created using liquibase scripts (to be fixed by [TMT-919](https://jira.thehyve.nl/secure/RapidBoard.jspa?rapidView=124&projectKey=TMT&view=detail&selectedIssue=TMT-919)
> Make scan and cache rebuild tasks optional for after_data_loading_update

- transmart-data/test_data/studies/SHARED_CONCEPTS_STUDY_A/i2b2demodata/study.tsv
- transmart-rest-api-e2e/src/test/groovy/tests/rest/v2/NotificationsSpec.groovy
- transmart-rest-api-e2e/src/test/groovy/tests/rest/v2/StudiesSpec.groovy
There are still 3 tests failing because of the broken EHR test study:
- ["query observations based on time constraint between startDates"](https://github.com/thehyve/transmart-core/blob/d783b7b58287481324ddcfa5a683693c8b84dfa1/transmart-rest-api-e2e/src/test/groovy/tests/rest/v2/hypercube/TimeConstraintSpec.groovy#L69)
- [ "SubSelectionConstraint.class"](https://github.com/thehyve/transmart-core/blob/69fb80c24b68425243559e676ed4cd2477710b9b/transmart-rest-api-e2e/src/test/groovy/tests/rest/v2/hypercube/ConstraintSpec.groovy#L418)
- ["supported fields"](https://github.com/thehyve/transmart-core/blob/d783b7b58287481324ddcfa5a683693c8b84dfa1/transmart-rest-api-e2e/src/test/groovy/tests/rest/v2/SupportedFieldsSpec.groovy#L20)
> Rest Api e2e tests updates

- transmart-core-api/src/main/groovy/org/transmartproject/core/multidimquery/query/NormaliseConstraintRewriter.groovy
- transmart-core-db/src/test/groovy/org/transmartproject/db/multidimquery/QueryRewriterSpec.groovy
The rule is not valid when the subselection dimension is
different from its parent dimension.
> Fix invalid constraint rewrite rule.

- transmart-core-db/grails-app/services/org/transmartproject/db/clinical/PatientSetService.groovy
When creating a patient set with `subjectIds` (identifiers in the patient mapping table), the API server fails on unknown relation `patient_mapping` when running with Docker and Liquibase.
This change fixes the issue.
> Fix creating patient sets based on patient mapping identifiers.
